[tool.poetry]
name = "domainprops"
version = "0.1.2"
description = "Parse domain name properties."
authors = ["Viktor Persson <viktor.persson@arcsin.se>"]
readme = "README.md"
repository = "https://github.com/vikpe/domainprops"
keywords = ["domains","domain names","parse"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Internet",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", allow-prereleases = true}
pytest = "^5.3.5"
pytest-cov = "^2.8"
pytest-sugar = "^0.9.2"
tox = "^3.14"
tox-pyenv = "^1.1"

[tool.black]
line-length = 88
target-version = ['py36', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
